name: registro_ponto_frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2
  go_router: ^17.2.3
  dio: ^5.9.2
  flutter_secure_storage: ^10.2.0
  equatable: ^2.0.8
  pretty_dio_logger: ^1.4.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  riverpod_generator: ^4.0.3
  riverpod_lint: ^3.1.3
  mocktail: ^1.0.5

flutter:
  uses-material-design: true

  assets:
    - assets/brand/app_brand_icon.png